version: '3.8'

services:
  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    command:
      - redis-server
      - --requirepass
      - "${REDIS_PASSWORD}"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      NODE_ENV:       "production"
      PORT:           "${PORT}"
      SESSION_SECRET: "${SESSION_SECRET}"
      EVE_CLIENT_ID:  "${EVE_CLIENT_ID}"
      EVE_SECRET_KEY: "${EVE_SECRET_KEY}"
      EVE_CALLBACK_URL: "${EVE_CALLBACK_URL}"
      MONGO_URI:      "${MONGO_URI}"
      REDIS_URL:      "${REDIS_URL}"
    depends_on:
      - mongo
      - redis

  worker:
    build: .
    command: npm run start:worker
    environment:
      NODE_ENV:  "production"
      MONGO_URI: "${MONGO_URI}"
      REDIS_URL: "${REDIS_URL}"
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      REACT_APP_API_BASE: "${REACT_APP_API_BASE}"
    depends_on:
      - backend

volumes:
  mongo-data:
  redis-data:
